config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/home'
  root 'pages#home'
  get 'pages/about'
  get '/search', to: 'pages#search', as: 'search'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users , except: [:new]
  
  get 'login', to: 'sessionns#new'
  post 'login', to: 'sessionns#create'
  delete 'logout', to: 'sessionns#destroy'
  
  resources :categories, except: [:destroy]

end

app/models/article.rb
# frozen_string_literal: true

class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }, uniqueness: {case_sensitive: false}
  validates :description, presence: true, length: { minimum: 3, }
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  skip_before_action :verify_authenticity_token


  def new
    @article = Article.new
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5) 
     #if params[:search].present?
     #  search = params[:search].downcase
      # @articles = Article.where([("description LIKE?" || "title LIKE?"),"%#{params[:search].downcase!}%"])
     #end
  end

  def edit

  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article was Successfully Created'
      redirect_to @article
      #render json: { result: true, msg: @article}, status: :created
    else
      render 'new'
      #render json: {result: false, article: @article.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = 'Article was successfully deleted'
    redirect_to articles_path
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def show

  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user and !current_user.adimin?
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to root_path
    end
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
        <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
                <div class="well well-lg">
                    <div class="article-title">
                        <%= link_to article.title, article_path(article) %>
                    </div>
                    <div class="article-body">
                        <%= truncate(article.description, length: 100) %>
                        <div class="article-meta-details">
                        <small>Created by: <%= article.user.username if article.user %>,
                        <%= time_ago_in_words(article.created_at) %> ago,
                        last updated: <%= time_ago_in_words(article.updated_at) %>  ago </small>
                    </div>
                </div>
                <% if article.categories.any? %>
                    <p>Categories: <%= render article.categories %></p>
                <% end %>

                <% if logged_in? && (current_user == article.user || current_user.adimin?) %>
                    <div class="article-actions">
                        <%= link_to "edit this article" , edit_article_path(article), class: "btn btn-xs btn-primary" %> 
                        <%= link_to "Delete this article", article_path(article), method: :delete, data: 
                                                            {confirm: "are you sure want to delete this article?"}, 
                                                            class: "btn btn-xs btn-danger"%>
                    </div>
                <% end %>
                </div>
            </div>
        </div>
    <% end %> 

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj:@article %>

<div class='row'>
    <div class='col-xs-12'>
<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <div class= "control-label col-sm-2">
                <%= f.label :title %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class= "control-label col-sm-2">
                <%= f.label :description %>
            </div>
            <div class="col-sm-8">
                <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of article" %>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class= "control-label col-sm-2">
                    <%= f.label "Category :" %>
                </div>
                <div class="col-sm-8">
                    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                    <% cb.label(class:"checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class:'btn btn-primary btn-lg' %>
            </div>
        </div>
<% end %>
        <div class="col-xs-4 col-xs-offset-4" >
            |<%= link_to 'Cancel Request and return to article listing', articles_path %>|
    </div>
</div>
</div>
<%= link_to 'about', "http://localhost:3000/pages/about" %>|
<%= link_to 'Home', "http://localhost:3000/pages/home" %>

app/views/articles/edit.html.erb
<h1 align="center"> Edit Existing Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center"> Listing All article</h1>
<div align="center">
<!-- <%= form_tag articles_path, :method => 'get' do %>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Search" %>
<% end %> -->
<%= will_paginate %>    
</div>
<%= render 'article', obj: @articles%>
<%= will_paginate %>

app/views/articles/new.html.erb
<h1 align="center"> Create an Article </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
    <% if @article.user %>
        <ul class="listing">
            <div class="row center">
                <div class="col-md-4 col-md-offset-4">
                    <li>Created by:</li>
                    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                    <li class="article-title">
                        <%= link_to @article.user.username, user_path(@article.user) %>
                    </li>
                    <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
                </div>
            </div>
        </ul>
    <% end %>
    <h4 class="center description"><strong>Description: </strong></h4>
    <%= simple_format(@article.description) %>
    <% if @article.categories.any? %>
        <p>Categories: <%= render @article.categories %></p> <!-- @article.categories link to categories/_category.html.erb -->
    <% end %>
    <div class="article-actions">
        <% if logged_in? && (current_user == @article.user || current_user.adimin?) %>
            <%= link_to "edit this article" , edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
            <%= link_to "Delete this article", article_path(@article), method: :delete, data: 
                                                {confirm: "are you sure want to delete this article?"}, 
                                                class: "btn btn-xs btn-danger" %>
        <% end %>
            <%= link_to 'back to article listing', articles_path, class: "btn btn-xs btn-success" %>
    </div>
</div>